name: Vivalazer
description: A new Flutter project.
author: Bruno Silva Carvalho <bruno.silva.carvalho@outlook.com.br>

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  curved_navigation_bar: ^0.3.1
  provider: ^3.1.0
  floating_search_bar: ^0.2.0
  rxdart:
  dio:
  progress_button: ^0.0.1
  flutter_login: ^1.0.4
  google_maps_flutter: ^0.5.11
  http: ^0.12.0+1
  json_serializable: ^2.0.2
  map_overlay: ^0.0.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true