name: velhapp
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  http: ^0.11.3+16
  curved_navigation_bar: ^0.3.1
  provider: 3.0.0+1
  floating_search_bar: ^0.2.0
  shared_preferences: ^0.5.4+5
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true