INSERT INTO tb_tipo_evento VALUES 
(1,'privado'),
(2,'publico');

INSERT INTO tb_preferencia VALUES
(1,'Viagens'),
(2,'Teatro'),
(3,'Shows'),
(4,'Bingo'),
(5,'Encontros'),
(6,'Bazar'),
(7,'Caminhada Guiada'),
(8,'Competição Esportiva'),
(9,'Congresso'),
(10,'Corrida'),
(11,'Inauguração'),
(12,'Exposição'),
(13,'Comício'),
(14,'Comédia Stand-Up'),
(15,'Cabaré'),
(16,'Arte Performática Artística'),
(17,'Cultural'),
(18,'Cursos Livres'),
(19,'Discoteca'),
(20,'Evento Religioso'),
(21,'Feira de Negócios'),
(22,'Feira Gastronômica'),
(23,'Festa Beneficente'),
(24,'Festivais'),
(25,'Hackathon'),
(26,'Improvisação '),
(27,'Leilão'),
(28,'Networking'),
(29,'Projeção Cinematográfica'),
(30,'Sarau'),
(31,'Seminário'),
(32,'Sessão de Autógrafos'),
(33,'Torneio'),
(34,'Show de Talentos'),
(35,'Sessão de Degustação'),
(36,'Feira de Consumidores'),
(37,'Voluntariado');

INSERT INTO tb_tipo_contato VALUES 
(1,'E-mail'),
(2,'Telefone celular'),
(3,'Telefone fixo'),
(4,'Telefone comercial'),
(5,'Fax');